import type { Metadata } from "next";
import localFont from "next/font/local";
import { Sora, Space_Mono } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const space_mono = Space_Mono({
  subsets: ["latin"],
  weight:["400","700"],
  variable:"--font_spaceMono"
});

const sora = Sora({
  subsets: ["latin"],
  variable:"--font_sora"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} ${space_mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
